# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='huc12_code',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='HUC 12 ID'),
        ),
    ]
