# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0003_auto_20180925_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='focus_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishpass.FocusArea'),
        ),
    ]
