# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0005_barrier_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariobarrier',
            name='action',
            field=models.CharField(choices=[('consider', 'Consider'), ('include', 'Include in solution'), ('exclude', 'Exclude from solution')], default='consider', max_length=30),
        ),
    ]
