# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0006_scenariobarrier_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ownership_input',
        ),
        migrations.AddField(
            model_name='project',
            name='ownership_input_checkboxes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
