# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0007_auto_20181002_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ownership_input',
            field=models.BooleanField(default=False, verbose_name='Select ownership types'),
        ),
    ]
