# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0008_project_ownership_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='focus_region',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_area',
        ),
        migrations.AddField(
            model_name='project',
            name='target_area_input',
            field=models.TextField(blank=True, default=None, help_text='list of FocusArea IDs that make up the target area geometry', null=True),
        ),
    ]
