# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0009_auto_20181003_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('optgap', models.FloatField(verbose_name='percent optimality gap')),
                ('ptnl_habitat', models.FloatField(verbose_name='potential habitat')),
                ('netgain', models.FloatField(verbose_name='net gain')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReportBarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrier_id', models.CharField(max_length=50)),
                ('action', models.IntegerField()),
                ('project_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishpass.ProjectReport')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[('budget', 'Fixed Budget'), ('batch', 'Ranged Budget')], default='budget', max_length=40, verbose_name='Fixed Budget or Range'),
        ),
        migrations.AlterField(
            model_name='project',
            name='geometry_final_area',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Total Area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planning_units',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Planning Unit IDs'),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishpass.Project'),
        ),
    ]
