# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0010_auto_20181005_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSpeciesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blocked Species Types',
                'verbose_name': 'Blocked Species Type',
            },
        ),
        migrations.CreateModel(
            name='TreatmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Treatment Statuses',
                'verbose_name': 'Treatment Status',
            },
        ),
        migrations.AlterModelOptions(
            name='barrier',
            options={'verbose_name': 'Barrier', 'verbose_name_plural': 'Barriers'},
        ),
        migrations.AlterModelOptions(
            name='barriercost',
            options={'verbose_name': 'Barrier Cost', 'verbose_name_plural': 'Barrier Costs'},
        ),
        migrations.AlterModelOptions(
            name='barrierstatus',
            options={'verbose_name': 'Barrier Status', 'verbose_name_plural': 'Barrier Statuses'},
        ),
        migrations.AlterModelOptions(
            name='barriertype',
            options={'verbose_name': 'Barrier Type', 'verbose_name_plural': 'Barrier Types'},
        ),
        migrations.AlterModelOptions(
            name='focusarea',
            options={'verbose_name': 'Focus Area', 'verbose_name_plural': 'Focus Areas'},
        ),
        migrations.AlterModelOptions(
            name='ownershiptype',
            options={'verbose_name': 'Ownership Type', 'verbose_name_plural': 'Ownership Types'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectreport',
            options={'verbose_name': 'Project Report', 'verbose_name_plural': 'Project Reports'},
        ),
        migrations.AlterModelOptions(
            name='projectreportbarrier',
            options={'verbose_name': 'Project Report Barrier', 'verbose_name_plural': 'Project Report Barriers'},
        ),
        migrations.AlterModelOptions(
            name='scenariobarrier',
            options={'verbose_name': 'Project-Specific Barrier Setting', 'verbose_name_plural': 'Project-Specific Barrier Settings'},
        ),
        migrations.AlterModelOptions(
            name='scenariobarrierstatus',
            options={'verbose_name': 'Project-Specific Barrier Status Setting', 'verbose_name_plural': 'Project-Specific Barrier Status Settings'},
        ),
        migrations.AlterModelOptions(
            name='scenariobarriertype',
            options={'verbose_name': 'Project-Specific Barrier Type Setting', 'verbose_name_plural': 'Project-Specific Barrier Type Settings'},
        ),
        migrations.AddField(
            model_name='barrier',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Image Link'),
        ),
        migrations.AddField(
            model_name='barrier',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='post_mile',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Post Mile Marker'),
        ),
        migrations.AddField(
            model_name='barrier',
            name='road',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='treatment_recommendation',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Treatment Recommendation'),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='assessed_by',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Assessed By'),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='passage_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Passage ID'),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='protocol',
            field=models.CharField(blank=True, default=None, help_text='How the barrier was identified', max_length=255, null=True, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='site_name',
            field=models.CharField(blank=True, default=None, help_text='Name of the site at which barrier is located, or name of the barrier itself', max_length=255, null=True, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='stream_name',
            field=models.CharField(blank=True, default=None, help_text='The name of the waterbody obstructed by this barrier', max_length=255, null=True, verbose_name='Stream Name'),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='tributary_to',
            field=models.CharField(blank=True, default=None, help_text='The waterbody that this obstructed waterbody flows into', max_length=255, null=True, verbose_name='Tributary To'),
        ),
        migrations.AddField(
            model_name='barrier',
            name='species_blocked',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishpass.BlockedSpeciesType', verbose_name='Blocked Species Type'),
        ),
        migrations.AddField(
            model_name='barrier',
            name='treatment_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishpass.TreatmentStatus', verbose_name='Treatment Status'),
        ),
    ]
