# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 23:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0012_auto_20181009_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='barriercost',
            name='barrier_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishpass.BarrierStatus', verbose_name='Barrier Status'),
        ),
        migrations.AddField(
            model_name='barriercost',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='barriercost',
            name='site_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishpass.BarrierType', verbose_name='Barrier Type'),
        ),
        migrations.AlterField(
            model_name='barriercost',
            name='cost',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
