# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0013_auto_20181009_1659'),
        ('fishpass', '0011_auto_20181009_1259'),
    ]

    operations = [
    ]
