# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0014_merge_20181010_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barriercost',
            options={'verbose_name': 'Barrier Specific Override', 'verbose_name_plural': 'Barrier Specific Overrides'},
        ),
        migrations.AlterModelOptions(
            name='blockedspeciestype',
            options={'verbose_name': 'Lookup - Blocked Species Type', 'verbose_name_plural': 'Lookup - Blocked Species Types'},
        ),
        migrations.AlterModelOptions(
            name='focusarea',
            options={'verbose_name': 'Lookup - Focus Area', 'verbose_name_plural': 'Lookup - Focus Areas'},
        ),
        migrations.AlterModelOptions(
            name='ownershiptype',
            options={'verbose_name': 'Lookup - Ownership Type', 'verbose_name_plural': 'Lookup - Ownership Types'},
        ),
        migrations.AlterModelOptions(
            name='treatmentstatus',
            options={'verbose_name': 'Lookup - Treatment Status', 'verbose_name_plural': 'Lookup - Treatment Statuses'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='target_area_input',
            new_name='target_area',
        ),
        migrations.AlterField(
            model_name='barriercost',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='project',
            name='geometry_final_area',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Total Area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planning_units',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Planning Unit IDs'),
        ),
    ]
