# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0016_auto_20181013_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='max_budget',
            new_name='budget_max',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='min_budget',
            new_name='budget_min',
        ),
    ]
