# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 00:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0017_auto_20181015_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreportbarrier',
            name='estimated_cost',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='projectreportbarrier',
            name='post_passability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projectreportbarrier',
            name='pre_passability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='batch_increment',
            field=models.IntegerField(blank=True, default=10000, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_max',
            field=models.IntegerField(blank=True, default=100000, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_min',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='ownership_input_checkboxes',
            field=models.TextField(blank=True, default="['3', '5', '23', '4', '99', '7', '98', '18', '22', '17', '6', '20', '10', '12', '28', '9', '16', '8', '2']", null=True),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='netgain',
            field=models.FloatField(default=0.0, verbose_name='net gain'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='optgap',
            field=models.FloatField(default=0.0, verbose_name='percent optimality gap'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='ptnl_habitat',
            field=models.FloatField(default=0.0, verbose_name='potential habitat'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectreportbarrier',
            name='action',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scenariobarrier',
            name='action',
            field=models.CharField(choices=[('consider', 'Consider for solution'), ('include', 'Include in solution'), ('exclude', 'Exclude from solution')], default='consider', max_length=30),
        ),
    ]
