# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0019_barrierstatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='overflow',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional Info'),
        ),
    ]
