# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0020_barrier_overflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('HUC02', 'HUC02'), ('HUC04', 'HUC04'), ('HUC06', 'HUC06'), ('HUC08', 'HUC08'), ('HUC10', 'HUC10'), ('HUC12', 'HUC12'), ('Boundary', 'Boundary'), ('County', 'County'), ('Region', 'Region'), ('Coho', 'Coho'), ('Chinook', 'Chinook'), ('Chinook_Spring', 'Chinook_Spring'), ('Chinook_Fall', 'Chinook_Fall'), ('Steelhead', 'Steelhead')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ownership_input_checkboxes',
            field=models.TextField(blank=True, default="['18', '20', '10', '28', '23', '2', '3', '22', '7', '17', '9', '98', '4', '99', '5', '8', '16', '6', '12']", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='spatial_organization',
            field=models.CharField(blank=True, choices=[('HUC02', 'HUC02'), ('HUC04', 'HUC04'), ('HUC06', 'HUC06'), ('HUC08', 'HUC08'), ('HUC10', 'HUC10'), ('HUC12', 'HUC12'), ('Boundary', 'Boundary'), ('County', 'County'), ('Region', 'Region'), ('Coho', 'Coho'), ('Chinook', 'Chinook'), ('Chinook_Spring', 'Chinook_Spring'), ('Chinook_Fall', 'Chinook_Fall'), ('Steelhead', 'Steelhead')], default=None, max_length=50, null=True),
        ),
    ]
