# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 21:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishpass', '0021_auto_20190319_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_run',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scenariobarrier',
            name='action',
            field=models.CharField(choices=[('consider', 'Free'), ('include', 'Force-In'), ('exclude', 'Force-Out')], default='consider', max_length=30),
        ),
        migrations.AlterField(
            model_name='scenariobarrier',
            name='cost',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='scenariobarrier',
            name='post_pass',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='PostPass'),
        ),
        migrations.AlterField(
            model_name='scenariobarrier',
            name='pre_pass',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='PrePass'),
        ),
    ]
